### ISSUE TITLE
skript-packet make parsering impossible

### ISSUE THREAD

**Issue by AKtomik** [Anarchick/skript-packet#25]
### hum ?

I use **Skript 2.6.4** and get the same type of error as #24.
I make here a new issue to give more details about this error and to find when happend.

First, **This error is caused by skript-packet** beacause, happend only with skript-packet enabled.

Then, this error happend when load scripts (in the server start, when reloading, when enableing), and the script in question isnt loaded (like disabled), same if skript say "scuessfully loaded" (see **error** section).

So after some try, this happend exactly when skript try to parse another event than an load/unload event.

### Somes examples to understand

script 1:
```

```
No error (say its empty), script correcly loaded.

script 2:
```
on join:
	send "ok"
```
The error one time, the script isnt loaded.

script 3:
```
on load:
	send "hi" to the console
on unload:
	send "unhi" to the console
```
No error, script correcly loaded.

script 4:
```
on load:
	send "hi" to the console
on unload:
	send "unhi" to the console

on join:
	send "ok"
on join:
	send "ok"
```
The error one time, the entire script isnt loaded.

### The error
using skript 2.6.4 and skript packet 2.1.1, whitout any other addons, paper 1.19.4 (538 git version)
```
[INFO] [Skript] Reloading Test.sk...
[ERROR] #!#!
[ERROR] #!#! [Skript] Severe Error:
[ERROR] #!#! Could not load Test.sk
[ERROR] #!#!
[ERROR] #!#! Something went horribly wrong with Skript.
[ERROR] #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[ERROR] #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[ERROR] #!#! Here is full list of them:
[ERROR] #!#! Skript-Packet v2.1.1 (www.github.com/Anarchick/skript-packet)
[ERROR] #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[ERROR] #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[ERROR] #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[ERROR] #!#! In that case, you will be given instruction on how should you report it.
[ERROR] #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[ERROR] #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[ERROR] #!#!
[ERROR] #!#! Stack trace:
[ERROR] #!#! java.lang.RuntimeException: pattern compiling exception, element class: fr.anarchick.skriptpacket.elements.expressions.utility.ExprNumbersAsArray
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:522)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:169)
[ERROR] #!#! at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[ERROR] #!#! at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[ERROR] #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:907)
[ERROR] #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:870)
[ERROR] #!#! at net.minecraft.server.dedicated.DedicatedServer.bh(DedicatedServer.java:501)
[ERROR] #!#! at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)
[ERROR] #!#! at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[ERROR] #!#! at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[ERROR] #!#! at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[ERROR] #!#! at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: invalid parse mark at 2 [pattern: 0Â¦Int[eger]|1Â¦Float|2Â¦Long|3Â¦Double|4Â¦Short|5Â¦Byte]
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:120)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:89)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[ERROR] #!#! at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1254)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:522)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:169)
[ERROR] #!#! at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[ERROR] #!#! at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[ERROR] #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:907)
[ERROR] #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:870)
[ERROR] #!#! at net.minecraft.server.dedicated.DedicatedServer.bh(DedicatedServer.java:501)
[ERROR] #!#! at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)
[ERROR] #!#! at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[ERROR] #!#! at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[ERROR] #!#! at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[ERROR] #!#! at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] #!#! Caused by: java.lang.NumberFormatException: For input string: "0Â"
[ERROR] #!#! at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[ERROR] #!#! at java.base/java.lang.Integer.parseInt(Integer.java:668)
[ERROR] #!#! at java.base/java.lang.Integer.parseInt(Integer.java:786)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:118)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:89)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[ERROR] #!#! at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1254)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:522)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[ERROR] #!#! at Skript-2.6.4.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:169)
[ERROR] #!#! at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[ERROR] #!#! at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[ERROR] #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:907)
[ERROR] #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:870)
[ERROR] #!#! at net.minecraft.server.dedicated.DedicatedServer.bh(DedicatedServer.java:501)
[ERROR] #!#! at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)
[ERROR] #!#! at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[ERROR] #!#! at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[ERROR] #!#! at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[ERROR] #!#! at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] #!#!
[ERROR] #!#! Version Information:
[ERROR] #!#! Skript: 2.6.4 (latest)
[ERROR] #!#! Flavor: skriptlang-github
[ERROR] #!#! Date: 17:14:25.041218900
[ERROR] #!#! Bukkit: 1.19.4-R0.1-SNAPSHOT
[ERROR] #!#! Minecraft: 1.19.4
[ERROR] #!#! Java: 17.0.3.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.3.1+2-LTS-6)
[ERROR] #!#! OS: Linux amd64 5.15.96-mtxserv
[ERROR] #!#!
[ERROR] #!#! Server platform: Paper
[ERROR] #!#!
[ERROR] #!#! Current node: wait 1 tick (Test.sk, line 2)
[ERROR] #!#! Current item: null
[ERROR] #!#!
[ERROR] #!#! Thread: Server thread
[ERROR] #!#!
[ERROR] #!#! Language: english
[ERROR] #!#! Link parse mode: DISABLED
[ERROR] #!#!
[ERROR] #!#! End of Error.
[ERROR] #!#!
[INFO] [Skript] Successfully reloaded Test.sk. (2ms)
```

### So...

So, the use of any events (exept `load`/`unload` in my knowledge) make fail the skript parse when you use skript-packet.
So, you simpely cant use skript-packet, so it's a little urgent to patch that for make skript-packet usable.
So, Hoping its will be patch soon :+1:

**If you need any information about this bug, do not hesitate !**
**Thank you in advance for the support, and thank you for this so usefull addon ! 😄**
Cant use it make me a bit sad :/

**Comment by Anarchick** [comment]
Official fix with 2.1.2
