### ISSUE TITLE
Werid Packet Error

### ISSUE THREAD

**Issue by Dinoboy50** [Anarchick/skript-packet#34]
*[05:13:24 ERROR]: #!#! 
[05:13:24 ERROR]: #!#! [Skript] Severe Error:
[05:13:24 ERROR]: #!#! 
[05:13:24 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[05:13:24 ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[05:13:24 ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[05:13:24 ERROR]: #!#! 
[05:13:24 ERROR]: #!#! Stack trace:
[05:13:24 ERROR]: #!#! java.lang.IllegalStateException: Unable to set value of field private final boolean net.minecraft.network.protocol.game.PacketPlayOutAbilities.e
[05:13:24 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.set(DefaultFieldAccessor.java:44)
[05:13:24 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:359)
[05:13:24 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeSafely(StructureModifier.java:335)
[05:13:24 ERROR]: #!#!     at Skript-Packet-2.2.1.jar//fr.anarchick.skriptpacket.packets.PacketManager.setField(PacketManager.java:211)
[05:13:24 ERROR]: #!#!     at Skript-Packet-2.2.1.jar//fr.anarchick.skriptpacket.elements.expressions.packet.ExprPacketField.change(ExprPacketField.java:150)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:280)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:86)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:301)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:200)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.command.Commands$2.lambda$onPlayerChat$0(Commands.java:299)
[05:13:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftFuture.run(CraftFuture.java:88)
[05:13:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[05:13:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[05:13:24 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[05:13:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[05:13:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[05:13:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[05:13:24 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[05:13:24 ERROR]: #!#! Caused by: java.lang.ClassCastException: Cannot cast java.lang.Long to java.lang.Boolean
[05:13:24 ERROR]: #!#!     at java.base/java.lang.Class.cast(Class.java:3889)
[05:13:24 ERROR]: #!#!     at java.base/sun.invoke.util.ValueConversions.primitiveConversion(ValueConversions.java:252)
[05:13:24 ERROR]: #!#!     at java.base/sun.invoke.util.ValueConversions.unboxBoolean(ValueConversions.java:108)
[05:13:24 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.set(DefaultFieldAccessor.java:41)
[05:13:24 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:359)
[05:13:24 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeSafely(StructureModifier.java:335)
[05:13:24 ERROR]: #!#!     at Skript-Packet-2.2.1.jar//fr.anarchick.skriptpacket.packets.PacketManager.setField(PacketManager.java:211)
[05:13:24 ERROR]: #!#!     at Skript-Packet-2.2.1.jar//fr.anarchick.skriptpacket.elements.expressions.packet.ExprPacketField.change(ExprPacketField.java:150)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:280)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:86)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:301)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:200)
[05:13:24 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.command.Commands$2.lambda$onPlayerChat$0(Commands.java:299)
[05:13:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftFuture.run(CraftFuture.java:88)
[05:13:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[05:13:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[05:13:24 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[05:13:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[05:13:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[05:13:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[05:13:24 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[05:13:24 ERROR]: #!#! 
[05:13:24 ERROR]: #!#! Version Information:
[05:13:24 ERROR]: #!#!   Skript: 2.7.3 (OUTDATED)
[05:13:24 ERROR]: #!#!     Flavor: skriptlang-github
[05:13:24 ERROR]: #!#!     Date: 15:29:36.833117400
[05:13:24 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[05:13:24 ERROR]: #!#!   Minecraft: 1.19.4
[05:13:24 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[05:13:24 ERROR]: #!#!   OS: Linux amd64 6.2.0-36-generic
[05:13:24 ERROR]: #!#! 
[05:13:24 ERROR]: #!#! Server platform: Paper
[05:13:24 ERROR]: #!#! 
[05:13:24 ERROR]: #!#! Current node: null
[05:13:24 ERROR]: #!#! Current item: set [packet] field %number% [of %-packet%] to [[long:1]]
[05:13:24 ERROR]: #!#! Current trigger: function zomer (simple event) (t.sk, line 21)
[05:13:24 ERROR]: #!#! 
[05:13:24 ERROR]: #!#! Thread: Server thread
[05:13:24 ERROR]: #!#! 
[05:13:24 ERROR]: #!#! Language: english
[05:13:24 ERROR]: #!#! Link parse mode: DISABLED
[05:13:24 ERROR]: #!#! 
[05:13:24 ERROR]: #!#! End of Error.
[05:13:24 ERROR]: #!#!*

**Skript 2.7.3
Skript-packet 2.2.1
PLib 5.1**

Code

function zomer(p: player, i: number):
	set {_packet} to new play_server_abilities packet
	set field 0 of {_packet} to 1
	set field 1 of {_packet} to 0.05
	set field 2 of {_packet} to {_i}
	send {_p} packet {_packet}

**Comment by Anarchick** [comment]
I have tested in 1.21.1 and play_server_abilities has changed even if it's not indicated in protocol wiki.vg
The field 0 is not anymore a byte mask, it's replace by 4 boolean fields

When you have an issue with a packet, you should always show the content of a legit packet:
```java
# change your gamemode to F3+F4 between survival and creative to trigger this event
on packet event play_server_abilities:
    set {packet} to event-packet
    broadcast fields of {packet}
    broadcast fields classes of {packet}
```

The new packet format is this :
0 : boolean # is Invulerable ?
1 : boolean # is Flying ?
2 : boolean # has flight state enable ?
3 : boolean # is in Creative with instabreaks ?
4 : float # Fly speed
5 : float #FOV
